### PR TITLE
feat(deps): Stryker 0.4 upgrade

### PR DESCRIPTION
**Pull request by nicojs**
fix(deps): Update stryker version to 0.4
test(e2e): Add 2 test runs

### CODE REVIEW

**Comment by simondel** [comment]
Shouldn't we also upgrade the README to show the latest arguments and mutators?

**Comment by nicojs** [comment]
Good point! But i don't like keeping readme's in sync with each other. I think we should document `files`, `mutate` and `configFile` and redirect to stryker for all other options. Do you agree?

**Comment by simondel** [comment]
Yeah I think that's a good idea :)

**Comment by nicojs** [comment]
Ok, updated

**Comment by simondel** [comment]
It looks good! If you agree with my commit you can go ahead and merge :)

**Comment by nicojs** [comment]
Looks good! I also added a mention to [styker-mutator.github.io](stryker-mutator.github.io). Now that we have a homepage, we should mention it in each readme :+1:

**Pull request merged**
